// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: autorun.proto

package autorun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	RunOnStart    bool                   `protobuf:"varint,4,opt,name=runOnStart,proto3" json:"runOnStart,omitempty"`
	Repeat        bool                   `protobuf:"varint,5,opt,name=repeat,proto3" json:"repeat,omitempty"`
	Interval      uint64                 `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_autorun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autorun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_autorun_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateRequest) GetRunOnStart() bool {
	if x != nil {
		return x.RunOnStart
	}
	return false
}

func (x *CreateRequest) GetRepeat() bool {
	if x != nil {
		return x.Repeat
	}
	return false
}

func (x *CreateRequest) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_autorun_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autorun_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_autorun_proto_rawDescGZIP(), []int{1}
}

var File_autorun_proto protoreflect.FileDescriptor

const file_autorun_proto_rawDesc = "" +
	"\n" +
	"\rautorun.proto\"\xb3\x01\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x1e\n" +
	"\n" +
	"runOnStart\x18\x04 \x01(\bR\n" +
	"runOnStart\x12\x16\n" +
	"\x06repeat\x18\x05 \x01(\bR\x06repeat\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\x04R\binterval\"\x10\n" +
	"\x0eCreateResponse24\n" +
	"\aAutorun\x12)\n" +
	"\x06Create\x12\x0e.CreateRequest\x1a\x0f.CreateResponseB*Z(github.com/madhavan-raja/autorun/autorunb\x06proto3"

var (
	file_autorun_proto_rawDescOnce sync.Once
	file_autorun_proto_rawDescData []byte
)

func file_autorun_proto_rawDescGZIP() []byte {
	file_autorun_proto_rawDescOnce.Do(func() {
		file_autorun_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_autorun_proto_rawDesc), len(file_autorun_proto_rawDesc)))
	})
	return file_autorun_proto_rawDescData
}

var file_autorun_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_autorun_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: CreateRequest
	(*CreateResponse)(nil), // 1: CreateResponse
}
var file_autorun_proto_depIdxs = []int32{
	0, // 0: Autorun.Create:input_type -> CreateRequest
	1, // 1: Autorun.Create:output_type -> CreateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_autorun_proto_init() }
func file_autorun_proto_init() {
	if File_autorun_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_autorun_proto_rawDesc), len(file_autorun_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_autorun_proto_goTypes,
		DependencyIndexes: file_autorun_proto_depIdxs,
		MessageInfos:      file_autorun_proto_msgTypes,
	}.Build()
	File_autorun_proto = out.File
	file_autorun_proto_goTypes = nil
	file_autorun_proto_depIdxs = nil
}
