// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: autorun.proto

package autorun

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Autorun_Create_FullMethodName = "/Autorun/Create"
)

// AutorunClient is the client API for Autorun service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutorunClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type autorunClient struct {
	cc grpc.ClientConnInterface
}

func NewAutorunClient(cc grpc.ClientConnInterface) AutorunClient {
	return &autorunClient{cc}
}

func (c *autorunClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Autorun_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutorunServer is the server API for Autorun service.
// All implementations must embed UnimplementedAutorunServer
// for forward compatibility.
type AutorunServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedAutorunServer()
}

// UnimplementedAutorunServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutorunServer struct{}

func (UnimplementedAutorunServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAutorunServer) mustEmbedUnimplementedAutorunServer() {}
func (UnimplementedAutorunServer) testEmbeddedByValue()                 {}

// UnsafeAutorunServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutorunServer will
// result in compilation errors.
type UnsafeAutorunServer interface {
	mustEmbedUnimplementedAutorunServer()
}

func RegisterAutorunServer(s grpc.ServiceRegistrar, srv AutorunServer) {
	// If the following call panics, it indicates UnimplementedAutorunServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Autorun_ServiceDesc, srv)
}

func _Autorun_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutorunServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Autorun_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutorunServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Autorun_ServiceDesc is the grpc.ServiceDesc for Autorun service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Autorun_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Autorun",
	HandlerType: (*AutorunServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Autorun_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autorun.proto",
}
