// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Process struct {
	ID          int64
	Name        string
	Description sql.NullString
	Command     string
	Interval    int64
}
