// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processes.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addProcess = `-- name: AddProcess :one
INSERT INTO process (
  name, description, command, interval
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, name, description, command, interval
`

type AddProcessParams struct {
	Name        string
	Description sql.NullString
	Command     string
	Interval    int64
}

func (q *Queries) AddProcess(ctx context.Context, arg AddProcessParams) (Process, error) {
	row := q.db.QueryRowContext(ctx, addProcess,
		arg.Name,
		arg.Description,
		arg.Command,
		arg.Interval,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Command,
		&i.Interval,
	)
	return i, err
}

const deleteProcess = `-- name: DeleteProcess :exec
DELETE FROM process
WHERE id = ?
`

func (q *Queries) DeleteProcess(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProcess, id)
	return err
}

const getProcess = `-- name: GetProcess :one
SELECT id, name, description, command, interval FROM process
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProcess(ctx context.Context, id int64) (Process, error) {
	row := q.db.QueryRowContext(ctx, getProcess, id)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Command,
		&i.Interval,
	)
	return i, err
}

const listProcesses = `-- name: ListProcesses :many
SELECT id, name, description, command, interval FROM process
ORDER BY id
`

func (q *Queries) ListProcesses(ctx context.Context) ([]Process, error) {
	rows, err := q.db.QueryContext(ctx, listProcesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Process
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Command,
			&i.Interval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
